# List of European countries and their derivatives
countries_europe = {
    "Albania": ["Albania", "Albanian"],
    "Andorra": ["Andorra", "Andorran"],
    "Austria": ["Austria", "Austrian"],
    "Belarus": ["Belarus", "Belarusian"],
    "Belgium": ["Belgium", "Belgian"],
    "Bosnia and Herzegovina": ["Bosnia", "Bosnian", "Herzegovina", "Herzegovinian"],
    "Bulgaria": ["Bulgaria", "Bulgarian"],
    "Croatia": ["Croatia", "Croatian"],
    "Cyprus": ["Cyprus", "Cypriot"],
    "Czech Republic": ["Czech Republic", "Czechia", "Czech"],
    "Denmark": ["Denmark", "Danish", "Dane"],
    "Estonia": ["Estonia", "Estonian"],
    "Finland": ["Finland", "Finnish", "Finn"],
    "France": ["France", "French"],
    "Germany": ["Germany", "German"],
    "Greece": ["Greece", "Greek"],
    "Hungary": ["Hungary", "Hungarian"],
    "Iceland": ["Iceland", "Icelandic"],
    "Ireland": ["Ireland", "Irish"],
    "Italy": ["Italy", "Italian"],
    "Latvia": ["Latvia", "Latvian"],
    "Liechtenstein": ["Liechtenstein", "Liechtensteiner"],
    "Lithuania": ["Lithuania", "Lithuanian"],
    "Luxembourg": ["Luxembourg", "Luxembourgish"],
    "Malta": ["Malta", "Maltese"],
    "Moldova": ["Moldova", "Moldovan"],
    "Monaco": ["Monaco", "Monégasque", "Monegasque"],
    "Montenegro": ["Montenegro", "Montenegrin"],
    "Netherlands": ["Netherlands", "Dutch"],
    "North Macedonia": ["North Macedonia", "Macedonia", "Macedonian"],
    "Norway": ["Norway", "Norwegian"],
    "Poland": ["Poland", "Polish"],
    "Portugal": ["Portugal", "Portuguese"],
    "Romania": ["Romania", "Romanian"],
    "Russia": ["Russia", "Russian"],
    "San Marino": ["San Marino", "Sammarinese"],
    "Serbia": ["Serbia", "Serbian"],
    "Slovakia": ["Slovakia", "Slovak"],
    "Slovenia": ["Slovenia", "Slovenian"],
    "Spain": ["Spain", "Spanish"],
    "Sweden": ["Sweden", "Swedish", "Swede"],
    "Switzerland": ["Switzerland", "Swiss"],
    "Turkey": ["Turkey", "Turkish"],
    "Ukraine": ["Ukraine", "Ukrainian"],
    "United Kingdom": ["United Kingdom", "UK", "British", "England", "Scotland", "Wales", "Northern Ireland", "English", "Scottish", "Welsh", "Irish"],
    "Vatican City": ["Vatican City", "Vatican", "Holy See"]
}

countries_africa = {
    "Algeria": ["Algeria", "Algerian"],
    "Angola": ["Angola", "Angolan"],
    "Benin": ["Benin", "Beninese"],
    "Botswana": ["Botswana", "Botswanan"],
    "Burkina Faso": ["Burkina Faso", "Burkinabé"],
    "Burundi": ["Burundi", "Burundian"],
    "Cameroon": ["Cameroon", "Cameroonian"],
    "Cape Verde": ["Cape Verde", "Cabo Verde", "Cape Verdean"],
    "Central African Republic": ["Central African Republic", "CAR", "Central African"],
    "Chad": ["Chad", "Chadian"],
    "Comoros": ["Comoros", "Comorian"],
    "Congo (Democratic Republic)": ["Congo (Democratic Republic)", "DRC", "Democratic Republic of Congo", "Congolese"],
    "Congo (Republic)": ["Congo (Republic)", "Republic of Congo", "Congo-Brazzaville", "Congolese"],
    "Djibouti": ["Djibouti", "Djiboutian"],
    "Egypt": ["Egypt", "Egyptian"],
    "Equatorial Guinea": ["Equatorial Guinea", "Equatoguinean"],
    "Eswatini": ["Eswatini", "Swaziland", "Swazi"],
    "Ethiopia": ["Ethiopia", "Ethiopian"],
    "Gabon": ["Gabon", "Gabonese"],
    "Gambia": ["Gambia", "Gambian"],
    "Ghana": ["Ghana", "Ghanaian"],
    "Guinea": ["Guinea", "Guinean"],
    "Guinea-Bissau": ["Guinea-Bissau", "Bissau-Guinean"],
    "Ivory Coast": ["Ivory Coast", "Côte d'Ivoire", "Ivorian"],
    "Kenya": ["Kenya", "Kenyan"],
    "Lesotho": ["Lesotho", "Basotho"],
    "Liberia": ["Liberia", "Liberian"],
    "Libya": ["Libya", "Libyan"],
    "Madagascar": ["Madagascar", "Malagasy"],
    "Malawi": ["Malawi", "Malawian"],
    "Mali": ["Mali", "Malian"],
    "Mauritania": ["Mauritania", "Mauritanian"],
    "Mauritius": ["Mauritius", "Mauritian"],
    "Morocco": ["Morocco", "Moroccan"],
    "Mozambique": ["Mozambique", "Mozambican"],
    "Namibia": ["Namibia", "Namibian"],
    "Niger": ["Niger", "Nigerien"],
    "Nigeria": ["Nigeria", "Nigerian"],
    "Rwanda": ["Rwanda", "Rwandan"],
    "Sao Tome and Principe": ["Sao Tome and Principe", "São Tomé and Príncipe", "Santomean"],
    "Senegal": ["Senegal", "Senegalese"],
    "Seychelles": ["Seychelles", "Seychellois"],
    "Sierra Leone": ["Sierra Leone", "Sierra Leonean"],
    "Somalia": ["Somalia", "Somali"],
    "South Africa": ["South Africa", "South African"],
    "South Sudan": ["South Sudan", "South Sudanese"],
    "Sudan": ["Sudan", "Sudanese"],
    "Tanzania": ["Tanzania", "Tanzanian"],
    "Togo": ["Togo", "Togolese"],
    "Tunisia": ["Tunisia", "Tunisian"],
    "Uganda": ["Uganda", "Ugandan"],
    "Zambia": ["Zambia", "Zambian"],
    "Zimbabwe": ["Zimbabwe", "Zimbabwean"]
}

countries_asia_pacific = {
    "Afghanistan": ["Afghanistan", "Afghan"],
    "Australia": ["Australia", "Australian"],
    "Bangladesh": ["Bangladesh", "Bangladeshi"],
    "Bhutan": ["Bhutan", "Bhutanese"],
    "Brunei": ["Brunei", "Bruneian"],
    "Cambodia": ["Cambodia", "Cambodian"],
    "Fiji": ["Fiji", "Fijian"],
    "India": ["India", "Indian"],
    "Indonesia": ["Indonesia", "Indonesian"],
    "Japan": ["Japan", "Japanese"],
    "Kazakhstan": ["Kazakhstan", "Kazakh"],
    "Kiribati": ["Kiribati", "I-Kiribati"],
    "Laos": ["Laos", "Lao", "Laotian"],
    "Malaysia": ["Malaysia", "Malaysian"],
    "Maldives": ["Maldives", "Maldivian"],
    "Mongolia": ["Mongolia", "Mongolian"],
    "Myanmar": ["Myanmar", "Burma", "Burmese"],
    "Nepal": ["Nepal", "Nepali"],
    "New Zealand": ["New Zealand", "Kiwi", "New Zealander"],
    "North Korea": ["North Korea", "DPRK", "North Korean"],
    "Pakistan": ["Pakistan", "Pakistani"],
    "Palau": ["Palau", "Palauan"],
    "Papua New Guinea": ["Papua New Guinea", "PNG", "Papua New Guinean"],
    "Philippines": ["Philippines", "Filipino", "Filipina"],
    "Singapore": ["Singapore", "Singaporean"],
    "South Korea": ["South Korea", "ROK", "South Korean"],
    "Sri Lanka": ["Sri Lanka", "Sri Lankan"],
    "Thailand": ["Thailand", "Thai"],
    "Timor-Leste": ["Timor-Leste", "East Timor", "Timorese"],
    "Tonga": ["Tonga", "Tongan"],
    "Tuvalu": ["Tuvalu", "Tuvaluan"],
    "Uzbekistan": ["Uzbekistan", "Uzbek"],
    "Vanuatu": ["Vanuatu", "Ni-Vanuatu"],
    "Vietnam": ["Vietnam", "Vietnamese"]
}

countries_north_america = {
    "Antigua and Barbuda": ["Antigua and Barbuda", "Antiguan", "Barbudan"],
    "Bahamas": ["Bahamas", "Bahamian"],
    "Barbados": ["Barbados", "Barbadian"],
    "Belize": ["Belize", "Belizean"],
    "Canada": ["Canada", "Canadian"],
    "Costa Rica": ["Costa Rica", "Costa Rican"],
    "Cuba": ["Cuba", "Cuban"],
    "Dominica": ["Dominica", "Dominican"],
    "Dominican Republic": ["Dominican Republic", "Dominican"],
    "El Salvador": ["El Salvador", "Salvadoran"],
    "Grenada": ["Grenada", "Grenadian"],
    "Guatemala": ["Guatemala", "Guatemalan"],
    "Haiti": ["Haiti", "Haitian"],
    "Honduras": ["Honduras", "Honduran"],
    "Jamaica": ["Jamaica", "Jamaican"],
    "Mexico": ["Mexico", "Mexican"],
    "Nicaragua": ["Nicaragua", "Nicaraguan"],
    "Panama": ["Panama", "Panamanian"],
    "Saint Kitts and Nevis": ["Saint Kitts and Nevis", "Kittitian", "Nevisian"],
    "Saint Lucia": ["Saint Lucia", "Saint Lucian"],
    "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines", "Vincentian"],
    "Trinidad and Tobago": ["Trinidad and Tobago", "Trinidadian", "Tobagonian"],
    "United States": ["United States", "US", "USA", "American"]
}